---
title: "Homework 5"
output: html_notebook
---

## Configuración inicial
```{r}
# Preparing libraries
library(ggplot2)
library(dplyr)
library(tidyr)

# Loading dataframes
questions <- read.csv("questions.csv")
answers <- read.csv("answers.csv")
tags <- read.csv("tags.csv")
question_tags <- read.csv("question_tags.csv")
```

### 1. Left-joining questions and tags
```{r}
# 1.1. Relacione questions y question_tags usando las columnas id y question_id, respectivamente.
questions_with_tags <- left_join(questions, question_tags, by = c("id" = "question_id"))

# 1.2. Agregue una relación más para la tabla tags.
questions_with_tags <- left_join(questions_with_tags, tags, by = c("tag_id" = "id"))

# 1.3. Utilice replace_na para cambiar los NA en la columna tag_name a "only-r".
questions_with_tags <- replace_na(questions_with_tags, list(tag_name = "only-r"))

# 1.4. Por último, almacene el resultado en la variable questions_with_tags.
questions_with_tags
```
### 2. Comparing scores across tags
```{r}
# 2.1. Utilice questions_with_tags y aplique group_by para la variable tag_name.
# 2.2. Aplique summarize para obtener el score promedio de cada pregunta y asígnele el nombre mean_score.
# 2.3. Ordene mean_score en forma descendente.

questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score = mean(score)) %>%
  arrange(desc(mean_score))
```
### 3. Finding gaps between questions and answers
```{r}
# 3.1. Utilice inner_join para combinar las tablas questions y answers, luego aplique los sufijos "_question" y "_answer", respectivamente.
# 3.2. Agregue una nueva columna utilizando la función mutate. La nueva columna se llamará gap y contendrá la resta de creation_date_answer y creation_date_question. (creation_date_answer - creation_date_question).

question_answer <- inner_join(questions, answers, by = c("id" = "question_id"), suffix = c("_question", "_answer")) %>%
  mutate(gap = difftime(creation_date_answer, creation_date_question, units = "days"))

question_answer
```
### 4. Joining question and answer counts
```{r}
# 4.1. Cuente y ordene la columna question_id en la tabla de answers, luego almacene el resultado en la variable answer_counts.
answer_counts <- answers %>%
  count(question_id) %>%
  arrange(desc(n))

answer_counts

# 4.2. Relacione la tabla questions con answer_counts (utilice left_join).
question_answer_counts <- left_join(questions, answer_counts, by = c("id" = "question_id"))

question_answer_counts

# 4.3. Reemplace los valores NA en la columna n con ceros.
question_answer_counts$n[is.na(question_answer_counts$n)] <- 0

# 4.4. Por último almacene el resultado en la variable question_answer_counts
question_answer_counts
```
### 5. Joining questions, answers, and tags
```{r}
# 5.1. Combine question_tags con question_answer_counts usando inner_join.
# 5.2. Ahora, use otro inner_join para agregar la tabla tags.

question_answer_tags <- inner_join(question_answer_counts, question_tags, by = c("id" = "question_id")) %>%
  inner_join(question_answer_tags, tags, by = c("tag_id" = "id"), suffix = c("_qatags", "_tags"))

question_answer_tags
```

